version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - database_volume:/var/lib/postgresql/data

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./website:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  database_volume:
